runtime: custom
env: flex

service: my-service

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

beta_settings:
  cloud_sql_instances: "${{ secrets.GCLOUD_PROJECT_ID }}:us-central1:philippe"

env_variables:
  ASPNETCORE_ENVIRONMENT: Production
